name: Update README

on:
  repository_dispatch:
    types: [readme_updated]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout my_repo
      uses: actions/checkout@v2
      with:
        repository: 'Bpolat0/WebhookTest1'
        token: ${{ secrets.YOUR_SECRET }}

    - name: Checkout other_repo
      uses: actions/checkout@v2
      with:
        repository: 'Bpolat0/WebhookTest'
        path: 'other_repo'

    - name: Update README
      run: |
        # Get the specific line from other_repo's README.md
        line=$(sed -n 5p other_repo/README.md)  # Change 5 to the line number you want

        # Replace the specific line in my_repo's README.md
        sed -i "5s/.*/$line/" README.md  # Change 5 to the line number you want

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README.md"
        git push
