name: Update README

on:
  schedule:
    - cron: '* * * * *'  # Run this workflow every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: 'Bpolat0/WebhookTest1'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get README content from other repo
      id: get-readme
      run: |
        content=$(curl -H "Accept: application/vnd.github.VERSION.raw" https://api.github.com/repos/Bpolat0/WebhookTest/readme)
        echo "::set-output name=content::$content"

    - name: Update README
      run: |
        # Get the specific line from other repo's README.md
        line=$(echo "${{ steps.get-readme.outputs.content }}" | sed -n 5p)  # Change 5 to the line number you want

        # Replace the specific line in my_repo's README.md
        sed -i "5s/.*/$line/" README.md  # Change 5 to the line number you want

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README.md"
        git push
