name: Pull Changes from Another Repository

on:
  push:
    branches:
      - main  # İzlemek istediğiniz ana branch'i burada belirtin

jobs:
  pull-changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Pull changes from another repository
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git remote add other-repo https://github.com/Bpolat0/WebhookTest.git  # Değişiklikleri almak istediğiniz depo
        git fetch other-repo
        git checkout -b changes-from-other-repo other-repo/main  # İzlemek istediğiniz branch'i belirtin
        git checkout main
        git merge changes-from-other-repo
        git push origin main
